[package]
name = "embed-demo"
version = "0.0.1"
edition = "2021"

[dependencies]
cortex-m = "0.7.5"
cortex-m-rt = "0.7.5"
defmt = "0.3.9"
defmt-rtt = "0.4.1"
microbit-v2 = "0.15.1"
panic-halt = "1.0.0"
